# JoinMessagePlus - Simple Join-Message Plugin
#              
# BungeeSupport:
#   Ignore: true/false - Deactivate this option if you only like to have Bungee Join/Quit-Messages. To use this feature you have to enable BungeeCord in the spigot.yml. 
# JoinMessage:
#   Enabled: true/false - Should the Join-Message be enabled.
#   Message: '&6[&a+&6] %player_name%/%player_displayname%' - Your custom Join-Message.
# QuitMessage:
#   Enabled: true - Should the Quit-Message be enabled.
#   Message: '&6[&4-&6] %player_name%/%player_displayname%' - Your custom Quit-Message. 
#              
BungeeSupport:
  Enabled: false
JoinMessage:
  Enabled: true
  Message: '&6[&a+&6] %player_name%'
QuitMessage:
  Enabled: true
  Message: '&6[&4-&6] %player_name%'